FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["WorkSphereFrontend.csproj", "."]
RUN dotnet restore "./WorkSphereFrontend.csproj"

COPY . .
RUN dotnet publish "./WorkSphereFrontend.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
COPY --from=build /src/wwwroot ./wwwroot
ENTRYPOINT ["dotnet", "WorkSphereFrontend.dll"]