FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["WorkSphere.ApiGateway.csproj", "."]
RUN dotnet restore "./WorkSphere.ApiGateway.csproj"

COPY . .
RUN dotnet publish "./WorkSphere.ApiGateway.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "WorkSphere.ApiGateway.dll"]