FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["WebApplication1 WorkSphere.DepartmentService.csproj", "."]
RUN dotnet restore "./WebApplication1 WorkSphere.DepartmentService.csproj"

COPY . .
RUN dotnet publish "./WebApplication1 WorkSphere.DepartmentService.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "WebApplication1 WorkSphere.DepartmentService.dll"]